export default {
  watch: { title: 'Your grandfather\'s gold watch', max: 1, icon: '⏱' },
  ssn: { title: 'Social Security Card', max: 1, icon: '🆔', },
  restitutionreceipt: { title: 'Restitution Receipt', icon: '🔖' },
  birthcertificatereceipt: { title: 'Birth Certificate Order Receipt', icon: '🔖', },
  birthcertificate: { title: 'Birth Certificate', max: 1, icon: '📜', },
  fishinglicense: { title: 'Fishing License', max: 1, icon: '🐟' },
  stateid: { title: 'State ID Card', icon: '🆔' },
  plasmacard: { title: 'Plasma Donation Record', icon: '🆎', },
  halfwayhouseinvite: { title: 'Halfway House Invitation', hidden: true, icon: '🔖' },
  halfwayhousekey: { title: 'Halfway House Key', icon: '🔑' },
  rentalkey: { title: 'Key to your friend\'s apartment', icon: '🔑' },
  pouareq: { title: 'UA form from Parole Officer', icon: '📄' },
  pouapass: { title: 'UA results for Parole Officer', hidden: true },
  pouafail: { title: 'UA results for Parole Officer', hidden: true, },
  jobuareq: { title: 'UA form from Hiring Manager', icon: '📄' },
  jobuapass: { title: 'UA results for Hiring Manager', hidden: true, },
  jobuafail: { title: 'UA results for Hiring Manager', hidden: true, },
  debitcard: { title: 'Debit Card', icon: '💳', },
  workboots: { title: 'Work Boots', icon:  '👞', },
  navoucher: { title: 'Attendence Slip from Narcotics Anonymous', icon: '📄', },
  counselingvoucher: { title: 'Counseling Voucher', icon: '📄' },
  careervoucher: { title: 'Career Center Voucher', icon: '📄' },
  careercenterdemand: {  hidden: true },
  stateiddemand: { title: 'State ID Required Notice', hidden: true },
  birthcertificatedemand: { title: 'Birth Certificate Required Notice', hidden: true },
  ramen: { title: 'Ramen Noodles', icon: '🍜', },
  frozenfood: { title: 'Frozen Meal', icon: '🍛' },
  warehouseapplication: { title: 'Blank Warehouse Application', icon: '📄' },
  completedwarehouseapplication: { title: 'Completed Warehouse Application', icon: '📄' },
  jobid: { title: 'Job ID and Timecard', icon: '🆔' },
  joborientationinvite: { title: 'Job Orientation Invitation', icon: '🔖',  },
  paycheck: { title: 'A paper paycheck in the amount of $168', icon: '💵', },
  bagofdrugs: { title: 'A risky little package to deliver to the playground', icon: '💀' },
};